version: '3'

services:
  boombower-nginx:
    restart: always
    build: build/nginx
    image: boombower/nginx
    container_name: boombower-nginx
    volumes:
      - "./volumes/nginx/log/:/var/log/nginx/"
      - "./build/nginx/boombower.prod.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./build/certbot/www:/var/www/certbot/:ro"
      - "./build/certbot/conf/:/etc/nginx/ssl/:ro"
      - "..:/boombower:ro"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - boombower
    depends_on:
      - boombower-php-fpm

  boombower-php-fpm:
    build: build/php-fpm
    image: boombower/php-fpm
    container_name: boombower-php-fpm
    volumes:
      - "..:/boombower"
      - "./build/php-fpm/php.ini:/etc/php/8.1/fpm/php.ini:ro"
      - "./volumes/data:/opt/data"
    ports:
      - "127.0.0.1:9009:9000"
    networks:
      - boombower
    depends_on:
      - boombower-postgresql

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - "./build/certbot/www/:/var/www/certbot/:rw"
      - "./build/certbot/conf/:/etc/letsencrypt/:rw"
    networks:
      - boombower

  boombower-postgresql:
    build: build/postgresql
    image: boombower/db
    container_name: db
    environment:
      POSTGRES_PASSWORD: testpassW0000rdh
    volumes:
      - "./volumes/pgdata:/var/lib/postgresql/data"
      - "./volumes/data:/opt/data"
    tmpfs:
      - /run
      - /tmp
    ports:
      - "5432:5432"
    networks:
      - boombower

networks:
  boombower:
    external: true
